version: '3.5'

volumes:
  mongo-7:
    name: mongo-7

services:
  mongo7:
    image: mongo:7.0.5
    container_name: mongo-database
    restart: unless-stopped
    volumes:
      - mongo-7:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-}mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: mongo-demo
    ports:
      - ${MONGO_PORT:-0.0.0.0:27017}:27017
